--SQULQuery1-CREATE DATABASE

USE master;

CREATE DATABASE P_421_DDL
ON
(
	NAME		= P_421_DDL_dat,
	FILENAME	= 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\P_421_DDL.mdf',
	SIZE		= 8MB,
	MAXSIZE		= 500MB,
	FILEGROWTH	= 8MB
)
LOG ON
(
	NAME = P_421_DDL_log,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\P_421_DDL.log',
	SIZE = 8MB,
	MAXSIZE = 500MB,
	FILEGROWTH = 8MB
)